### PR TITLE
Grid Option

### PR DESCRIPTION
**Pull request by TravCav**
Option to generate a grid of every 10th chunk

### CODE REVIEW

**Comment by Eniripsa96** [comment]
Did you test this at all? I'm pretty sure this would just create impassable areas in the world since you can't build in those empty chunks.

**Comment by TravCav** [comment]
Shamefully no I didn't.  Did this as a last resort hoping it just worked or you'd have some feedback. Sorry about that.
I've spent all day trying to test it but I'm doing something wrong when I build my jar. Everything seems to compile fine but spigot's not loading it.  Even unaltered.   Java isn't my first language and this is my first go at a plugin and I have no experience with IntelliJ. Any suggestions?
By the way I was pleasantly surprised by the quality of your code.  Very well done.

**Comment by Eniripsa96** [comment]
When building it, make sure you include the "plugin.yml" and "config.yml" files as resources in the jar, since plugin.yml is required for Spigot to know how to load it and "config.yml" for plugin operations. For IntelliJ, it would be:

- File > Project Structure > Artifacts
- Select your jar artifact and click the + under the "Output Layout" tab
- Find and select the .yml files

Rebuilding should include them, can open up the jar to double check as well.

But in order to have something like this change work, where there's the gaps that can be built in, you would need to do a couple other things:

1. NoChunk needs to not override the "a" functions (or call super)
2. NoChunkProvider needs to save NoChunk instead of skipping it in saveChunk

**Comment by TravCav** [comment]
Awesome thanks! I'll give that a try.  
In light of this new info... is this a relevant feature for this plugin or does it diverge too much from it's purpose?

**Comment by Eniripsa96** [comment]
It contrasts with what it is currently trying to do, losing some of the features. Doing this, for instance, makes the plugin no longer let you disable it to get the chunks back and some people want to build in chunks. I suppose that's the point of configuration, so I suppose it's not too far off, though I wouldn't want such a specific implementation at least.

**Pull request closed without merging**
